# Generated by Django 5.2.17 on 2026-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='events_outb_status_75dd49_idx',
            old_name='events_outb_status_c18a9f_idx',
        ),
    ]
