# Generated by Django 5.2.17 on 2026-09-29 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_outb_status_c18a9f_idx_events_outb_status_75dd49_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_group', models.CharField(max_length=255)),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('partition', models.IntegerField()),
                ('offset', models.BigIntegerField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['consumer_group', '-processed_at'], name='events_cons_consume_210977_idx')],
                'constraints': [models.UniqueConstraint(fields=('consumer_group', 'event_id'), name='uniq_consumed_event_group_id')],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_group', models.CharField(max_length=255)),
                ('event_id', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('partition', models.IntegerField(blank=True, null=True)),
                ('offset', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['consumer_group', '-created_at'], name='events_dead_consume_ac489e_idx')],
            },
        ),
    ]
