# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_consumedevent_deadletterevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="publishing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="publishing_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="deadletterevent",
            constraint=models.UniqueConstraint(
                fields=("consumer_group", "topic", "partition", "offset"),
                name="uniq_dead_letter_source_offset",
            ),
        ),
    ]
