# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_outboxevent_publisher_lease_and_deadletter_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("publishing", "Publishing"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
