# Generated migration for ai_gateway app

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('cohere', 'Cohere'), ('mistral', 'Mistral'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('fireworks', 'Fireworks AI'), ('replicate', 'Replicate'), ('huggingface', 'HuggingFace'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('api_version', models.CharField(blank=True, max_length=50)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('supported_modalities', models.JSONField(blank=True, default=list)),
                ('rate_limits', models.JSONField(blank=True, default=dict)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('privacy_tier', models.CharField(default='standard', max_length=20)),
                ('credentials_ref', models.CharField(blank=True, max_length=255)),
                ('default_headers', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('circuit_breaker_threshold', models.PositiveIntegerField(default=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('modality', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('embedding', 'Embedding'), ('multimodal', 'Multimodal')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('disabled', 'Disabled'), ('beta', 'Beta')], default='active', max_length=20)),
                ('context_window', models.PositiveIntegerField(default=4096)),
                ('max_output_tokens', models.PositiveIntegerField(default=4096)),
                ('supports_tools', models.BooleanField(default=False)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('supports_json_mode', models.BooleanField(default=False)),
                ('supports_vision', models.BooleanField(default=False)),
                ('input_price_per_token', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('output_price_per_token', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('cached_input_price_per_token', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('image_price_per_unit', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('audio_price_per_second', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('quality_score', models.FloatField(default=0.0)),
                ('latency_p50_ms', models.PositiveIntegerField(default=0)),
                ('latency_p99_ms', models.PositiveIntegerField(default=0)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_gateway.provider')),
            ],
            options={
                'ordering': ('provider', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ModelPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(max_length=50)),
                ('routing_strategy', models.CharField(choices=[('cost_optimized', 'Cost Optimized'), ('quality_optimized', 'Quality Optimized'), ('latency_optimized', 'Latency Optimized'), ('balanced', 'Balanced'), ('manual', 'Manual Selection')], default='balanced', max_length=30)),
                ('fallback_policy', models.CharField(choices=[('none', 'No Fallback'), ('cheaper', 'Cheaper Model'), ('faster', 'Faster Model'), ('any_available', 'Any Available')], default='cheaper', max_length=20)),
                ('max_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('min_quality_score', models.FloatField(default=0.0)),
                ('allowed_regions', models.JSONField(blank=True, default=list)),
                ('required_capabilities', models.JSONField(blank=True, default=list)),
                ('plan_restrictions', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_providers', models.ManyToManyField(blank=True, to='ai_gateway.provider')),
                ('blocked_providers', models.ManyToManyField(blank=True, related_name='blocked_policies', to='ai_gateway.provider')),
                ('fallback_models', models.ManyToManyField(blank=True, related_name='fallback_policies', to='ai_gateway.model')),
                ('primary_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_policies', to='ai_gateway.model')),
            ],
            options={
                'ordering': ('task_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('job_step_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='queued', max_length=20)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveBigIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('audio_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('time_to_first_token_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('fallback_used', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_runs', to='ai_gateway.model')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_runs', to='ai_gateway.modelpolicy')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_runs', to='ai_gateway.provider')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('system', 'System Prompt'), ('task', 'Task Prompt'), ('template', 'Template'), ('chain_of_thought', 'Chain of Thought'), ('few_shot', 'Few-shot Examples'), ('guardrail', 'Guardrail')], max_length=30)),
                ('content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('model_constraints', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to='identity.user')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('accuracy', 'Accuracy'), ('faithfulness', 'Faithfulness'), ('hallucination', 'Hallucination'), ('toxicity', 'Toxicity'), ('bias', 'Bias'), ('latency', 'Latency'), ('cost', 'Cost'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_version', models.CharField(max_length=50)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('threshold_passed', models.BooleanField(blank=True, null=True)),
                ('results_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('run_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to='identity.user')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ai_gateway.model')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ai_gateway.prompt')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='ai_gateway_model_provider_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=('request_id',), name='ai_gateway_modelru_reques_abc123_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=('job_id',), name='ai_gateway_modelru_job_id__abc123_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=('provider', 'model', '-created_at'), name='ai_gateway_modelru_provid_abc123_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=('trace_id',), name='ai_gateway_modelru_trace_abc123_idx'),
        ),
    ]