# Generated by Django 5.2.17 on 2026-08-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='model',
            name='ai_gateway_model_provider_name_uniq',
        ),
        migrations.RenameIndex(
            model_name='modelrun',
            new_name='ai_gateway__request_445457_idx',
            old_name='ai_gateway_modelru_reques_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='modelrun',
            new_name='ai_gateway__job_id_ee780c_idx',
            old_name='ai_gateway_modelru_job_id__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='modelrun',
            new_name='ai_gateway__provide_8c3279_idx',
            old_name='ai_gateway_modelru_provid_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='modelrun',
            new_name='ai_gateway__trace_i_96857f_idx',
            old_name='ai_gateway_modelru_trace_abc123_idx',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('provider', 'name')},
        ),
    ]
