# Generated by Django 5.2.17 on 2026-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ai_gateway', '0003_seed_ai_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(
                choices=[
                    ('openai', 'OpenAI'),
                    ('anthropic', 'Anthropic'),
                    ('google', 'Google'),
                    ('cohere', 'Cohere'),
                    ('mistral', 'Mistral'),
                    ('perplexity', 'Perplexity'),
                    ('together', 'Together AI'),
                    ('fireworks', 'Fireworks AI'),
                    ('replicate', 'Replicate'),
                    ('huggingface', 'HuggingFace'),
                    ('ollama', 'Ollama (Local)'),
                    ('echo', 'Echo (Development)'),
                    ('custom', 'Custom'),
                ],
                max_length=30,
            ),
        ),
    ]
