# Generated by Django 5.2.17 on 2026-09-30 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0008_generated_image_ownership'),
        ('identity', '0006_seed_default_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required_capabilities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='ModelAliasTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('alias', 'priority'),
            },
        ),
        migrations.AddField(
            model_name='modelrun',
            name='model_alias',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_runs', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('cohere', 'Cohere'), ('mistral', 'Mistral'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('fireworks', 'Fireworks AI'), ('replicate', 'Replicate'), ('huggingface', 'HuggingFace'), ('ollama', 'Ollama (Local)'), ('llama', 'Llama (OpenAI-compatible)'), ('echo', 'Echo (Development)'), ('custom', 'Custom')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=['organization', '-created_at'], name='ai_gateway__organiz_fa5bd3_idx'),
        ),
        migrations.AddField(
            model_name='modelpolicy',
            name='model_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='ai_gateway.modelalias'),
        ),
        migrations.AddField(
            model_name='modelaliastarget',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='ai_gateway.modelalias'),
        ),
        migrations.AddField(
            model_name='modelaliastarget',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alias_targets', to='ai_gateway.model'),
        ),
        migrations.AddConstraint(
            model_name='modelaliastarget',
            constraint=models.UniqueConstraint(fields=('alias', 'model'), name='uniq_alias_target_model'),
        ),
        migrations.AddConstraint(
            model_name='modelaliastarget',
            constraint=models.UniqueConstraint(fields=('alias', 'priority'), name='uniq_alias_target_priority'),
        ),
    ]
