# Generated by Django 5.2.17 on 2026-10-04 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0011_generated_image_asset'),
        ('identity', '0006_seed_default_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('generate', 'Generate'), ('edit', 'Edit'), ('understand', 'Understand')], default='generate', max_length=12)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('model', models.CharField(default='auto', max_length=40)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('aspect_ratio', models.CharField(default='1:1', max_length=10)),
                ('style', models.CharField(blank=True, max_length=80)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('image_count', models.PositiveSmallIntegerField(default=1)),
                ('answer', models.TextField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to='identity.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ai_gateway.imagegeneration'),
        ),
        migrations.AddIndex(
            model_name='imagegeneration',
            index=models.Index(fields=['organization', 'owner', '-created_at'], name='ai_imagegen_owner_idx'),
        ),
    ]
