# Generated by Django 5.2.17 on 2026-08-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retentionrule',
            name='governance_retention_org_category_uniq',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='governance__organiz_680da9_idx',
            old_name='governance_aud_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='governance__actor_i_7f6e7f_idx',
            old_name='governance_aud_actor__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='governance__categor_e8e527_idx',
            old_name='governance_aud_catego_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='governance__resourc_b1555e_idx',
            old_name='governance_aud_resour_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='governance__organiz_d37293_idx',
            old_name='governance_con_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='governance__status_8df509_idx',
            old_name='governance_con_status_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyevent',
            new_name='governance__organiz_f32291_idx',
            old_name='governance_saf_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyevent',
            new_name='governance__user_id_ac1fe2_idx',
            old_name='governance_saf_user__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyevent',
            new_name='governance__categor_d0506d_idx',
            old_name='governance_saf_catego_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyevent',
            new_name='governance__severit_4237c3_idx',
            old_name='governance_saf_severi_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyevent',
            new_name='governance__action__500809_idx',
            old_name='governance_saf_action_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcase',
            new_name='governance__organiz_ada9b0_idx',
            old_name='governance_sup_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcase',
            new_name='governance__user_id_bb11e9_idx',
            old_name='governance_sup_user__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcase',
            new_name='governance__status_c4203b_idx',
            old_name='governance_sup_status_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcase',
            new_name='governance__assigne_88a0eb_idx',
            old_name='governance_sup_assigne_abc123_idx',
        ),
        migrations.AlterField(
            model_name='retentionrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
