# Generated by Django 5.2.17 on 2026-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_remove_retentionrule_governance_retention_org_category_uniq_and_more'),
        ('identity', '0003_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retentionrule',
            unique_together={('organization', 'data_category')},
        ),
    ]
