# Generated by Django 5.2.17 on 2026-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitlement',
            name='billing_entitlement_plan_feature_uniq',
        ),
        migrations.RenameIndex(
            model_name='creditledger',
            new_name='billing_cre_wallet__b2a83e_idx',
            old_name='billing_cre_wallet__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='creditledger',
            new_name='billing_cre_wallet__2bdeb1_idx',
            old_name='billing_cre_wallet__abc123_2',
        ),
        migrations.RenameIndex(
            model_name='creditledger',
            new_name='billing_cre_request_f676f7_idx',
            old_name='billing_cre_request_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='creditledger',
            new_name='billing_cre_job_id_f9dbc4_idx',
            old_name='billing_cre_job_id__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_organiz_7d8ebd_idx',
            old_name='billing_inv_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_provide_e6a7ea_idx',
            old_name='billing_inv_provide_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_organiz_28363b_idx',
            old_name='billing_pay_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_provide_f843f3_idx',
            old_name='billing_pay_provide_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_idempot_96c174_idx',
            old_name='billing_pay_idempot_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_organiz_e1331c_idx',
            old_name='billing_sub_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_provide_fcdcca_idx',
            old_name='billing_sub_provide_abc123_idx',
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('plan', 'feature')},
        ),
    ]
