# Generated by Django 5.2.17 on 2026-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_entitlement_billing_entitlement_plan_feature_uniq_and_more'),
        ('identity', '0003_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditwallet',
            index=models.Index(fields=['organization'], name='billing_cre_organiz_b1e572_idx'),
        ),
    ]
