# Generated by Django 5.2.17 on 2026-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_creditwallet_billing_cre_organiz_b1e572_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditwallet',
            name='monthly_spending_limit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='reason',
            field=models.CharField(choices=[('subscription_grant', 'Subscription Grant'), ('manual_topup', 'Manual Top-up'), ('auto_topup', 'Auto Top-up'), ('usage_chat', 'Chat Usage'), ('usage_image_gen', 'Image Generation'), ('usage_doc_render', 'Document Rendering'), ('usage_file_conv', 'File Conversion'), ('usage_search', 'Search'), ('usage_rag', 'RAG Query'), ('usage_workflow', 'Workflow Execution'), ('usage_storage', 'Storage'), ('usage_knowledge', 'Knowledge Ingestion'), ('usage_agent', 'Agent Run'), ('usage_analysis', 'Analysis Run'), ('usage_api', 'API Call'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('expired', 'Expired Credits'), ('promotion', 'Promotional Credits')], max_length=30),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='feature',
            field=models.CharField(choices=[('chat_messages', 'Chat Messages'), ('image_generations', 'Image Generations'), ('document_renders', 'Document Renders'), ('file_conversions', 'File Conversions'), ('knowledge_collections', 'Knowledge Collections'), ('knowledge_documents', 'Knowledge Documents'), ('search_queries', 'Search Queries'), ('rag_queries', 'RAG Queries'), ('api_calls', 'API Calls'), ('storage_gb', 'Storage (GB)'), ('workflow_executions', 'Workflow Executions'), ('priority_support', 'Priority Support'), ('custom_models', 'Custom Models'), ('sso', 'SSO'), ('audit_logs', 'Audit Logs'), ('agent_runs', 'Agent Runs'), ('analysis_runs', 'Analysis Runs')], max_length=50),
        ),
    ]
