# Generated by Django 5.2.17 on 2026-10-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_metering_fields'),
        ('identity', '0006_seed_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='credits_reversed',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_yearly_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_monthly_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_yearly_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('default_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('payment_method_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('livemode', models.BooleanField(default=False)),
                ('stripe_created', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'received_at'], name='billing_evt_status_idx')],
            },
        ),
    ]
