# Generated by Django 5.2.17 on 2026-08-13 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_owner_i_6da30c_idx',
            old_name='jobs_job_owner_cr_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_organiz_daf45b_idx',
            old_name='jobs_job_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_status_57b86b_idx',
            old_name='jobs_job_status__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_task_ty_0ce421_idx',
            old_name='jobs_job_task_ty_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_request_518f5c_idx',
            old_name='jobs_job_request_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_idempot_ddf6e2_idx',
            old_name='jobs_job_idempot_abc123_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='request_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='trace_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='callback',
            index=models.Index(fields=['status', 'next_retry_at'], name='jobs_callba_status_fd4389_idx'),
        ),
        migrations.AddIndex(
            model_name='callback',
            index=models.Index(fields=['job'], name='jobs_callba_job_id_7e4afe_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstep',
            index=models.Index(fields=['job', 'step_order'], name='jobs_jobste_job_id_69bceb_idx'),
        ),
        migrations.AddIndex(
            model_name='providerattempt',
            index=models.Index(fields=['job_step', 'attempt_number'], name='jobs_provid_job_ste_ead84c_idx'),
        ),
    ]
