# Generated by Django 5.2.17 on 2026-08-17 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_job_owner_cr_abc123_idx_jobs_job_owner_i_6da30c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='idempotency_key',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255),
        ),
    ]
