# Generated by Django 5.2.17 on 2026-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_callback_delivery_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='last_callback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='workflow_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='workflow_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['status', 'next_attempt_at'], name='jobs_wfrun_due_idx'),
        ),
    ]
