# Generated by Django 5.2.17 on 2026-08-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='integration_organiz_c917a1_idx',
            old_name='integrati_apike_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='integration_prefix_9f415f_idx',
            old_name='integrati_apike_prefix_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='connectoraccount',
            new_name='integration_organiz_1ab758_idx',
            old_name='integrati_connec_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='connectoraccount',
            new_name='integration_user_id_ee62be_idx',
            old_name='integrati_connec_user__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='connectoraccount',
            new_name='integration_status_685763_idx',
            old_name='integrati_connec_status_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='kafkaconsumer',
            new_name='integration_organiz_a293a4_idx',
            old_name='integrati_kafkac_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='webhook',
            new_name='integration_organiz_97aef7_idx',
            old_name='integrati_webho_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='integration_webhook_24fa1d_idx',
            old_name='integrati_webho_webhoo_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='integration_status_9e3d5d_idx',
            old_name='integrati_webho_status_abc123_idx',
        ),
        migrations.AlterField(
            model_name='kafkaconsumer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kafka_consumers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
