# Generated by Django 5.2.17 on 2026-09-30 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agentrun_tainted'),
        ('identity', '0006_seed_default_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_call_id', models.CharField(blank=True, max_length=100)),
                ('tool_name', models.CharField(max_length=150)),
                ('arguments', models.JSONField(default=dict)),
                ('arguments_digest', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('executed', 'Executed')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to='agents.agentrun')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_tool_approvals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to='identity.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tool_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ToolCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub App installation'), ('slack', 'Slack bot'), ('http', 'External HTTP API'), ('mcp', 'MCP server')], max_length=20)),
                ('name', models.SlugField(max_length=64)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_credentials', to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='McpServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', max_length=20)),
                ('discovered_tools', models.JSONField(blank=True, default=list)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('read_only_tools', models.JSONField(blank=True, default=list)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='identity.organization')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_servers', to='tools.toolcredential')),
            ],
        ),
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_call_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('agent', 'Agent run'), ('api', 'Direct API')], max_length=10)),
                ('tool_name', models.CharField(max_length=150)),
                ('side_effect', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('denied', 'Denied'), ('pending_approval', 'Pending approval'), ('rejected', 'Rejected by approver')], max_length=20)),
                ('deny_code', models.CharField(blank=True, max_length=60)),
                ('arguments_redacted', models.JSONField(default=dict)),
                ('arguments_digest', models.CharField(max_length=64)),
                ('output', models.TextField(blank=True)),
                ('output_digest', models.CharField(blank=True, max_length=64)),
                ('output_chars', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_invocations', to='agents.agentrun')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocations', to='tools.toolapproval')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='identity.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_invocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TenantToolPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_policies', to='identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'tool_name'), name='uniq_tool_policy_org_tool')],
            },
        ),
        migrations.AddIndex(
            model_name='toolapproval',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='tools_toola_organiz_2bcb73_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('tool_call_id', ''), _negated=True), fields=('agent_run', 'tool_call_id'), name='uniq_tool_approval_run_call'),
        ),
        migrations.AddConstraint(
            model_name='toolcredential',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'name'), name='uniq_tool_credential_org_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_mcp_server_org_slug'),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['organization', '-created_at'], name='tools_tooli_organiz_005256_idx'),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['agent_run', 'tool_call_id'], name='tools_tooli_agent_r_9d7801_idx'),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['status', '-created_at'], name='tools_tooli_status_fa1221_idx'),
        ),
    ]
