# Generated by Django 5.2.17 on 2026-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_seed_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='dial_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
