# Generated by Django 5.2.17 on 2026-08-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_job_owner_cr_abc123_idx_jobs_job_owner_i_6da30c_idx_and_more'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chunk',
            new_name='knowledge_c_documen_8e94ec_idx',
            old_name='knowledge_chu_documen_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='chunk',
            new_name='knowledge_c_collect_39228d_idx',
            old_name='knowledge_chu_collect_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='chunk',
            new_name='knowledge_c_vector__9fe033_idx',
            old_name='knowledge_chu_vector_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='collection',
            new_name='knowledge_c_organiz_491a09_idx',
            old_name='knowledge_col_organiz_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='knowledge_d_collect_779b84_idx',
            old_name='knowledge_doc_collect_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='knowledge_d_source__8f1e65_idx',
            old_name='knowledge_doc_source__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='knowledge_d_status_79949e_idx',
            old_name='knowledge_doc_status_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='knowledge_d_content_979d1d_idx',
            old_name='knowledge_doc_content_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='source',
            new_name='knowledge_s_collect_1ea19b_idx',
            old_name='knowledge_sou_collect_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='source',
            new_name='knowledge_s_status_894ae1_idx',
            old_name='knowledge_sou_status_abc123_idx',
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['job', 'citation_index'], name='knowledge_c_job_id_9b7291_idx'),
        ),
    ]
