# Generated by Django 5.2.17 on 2026-09-15 17:00

import pgvector.django.vector
from django.db import migrations, models

INDEX_NAME = 'chunk_embedding_hnsw_idx'


def enable_pgvector(apps, schema_editor):
    """Enable the Supabase `vector` extension before any vector column exists."""
    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector')


def create_embedding_index(apps, schema_editor):
    """Create the HNSW cosine index once ``knowledge_chunk.embedding`` exists."""
    schema_editor.execute(
        f'CREATE INDEX IF NOT EXISTS {INDEX_NAME} ON knowledge_chunk USING hnsw (embedding vector_cosine_ops)'
    )


def drop_embedding_index(apps, schema_editor):
    schema_editor.execute(f'DROP INDEX IF EXISTS {INDEX_NAME}')


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge', '0002_rename_knowledge_chu_documen_abc123_idx_knowledge_c_documen_8e94ec_idx_and_more'),
    ]

    # Order matters on a fresh database: extension -> columns -> index.
    operations = [
        migrations.RunPython(enable_pgvector, migrations.RunPython.noop),
        migrations.AddField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(create_embedding_index, drop_embedding_index),
    ]
