# Generated by Django 5.2.17 on 2026-10-03 19:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentrun_tainted'),
        ('jobs', '0006_callback_delivery_state'),
        ('knowledge', '0005_document_access_policy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chunk',
            name='knowledge_c_vector__9fe033_idx',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='vector_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='vector_ids',
        ),
        migrations.AddField(
            model_name='citation',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='document',
            name='index_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['agent_run', 'citation_index'], name='knowledge_c_agent_r_e20514_idx'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(('job__isnull', False), ('agent_run__isnull', False), _connector='OR'), name='citation_has_owner'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='knowledge_chunk_fts_idx'),
        ),
    ]
