# Generated by Django 5.2.17 on 2026-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_rag_fts_citations_and_recovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('url', 'Web URL'), ('text', 'Raw Text'), ('integration', 'Integration (synced by n8n)')], max_length=20),
        ),
    ]
