# Generated by Django 5.2.17 on 2026-08-16 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_alter_user_options_alter_user_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('template', models.CharField(default='general', max_length=100)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('download_url', models.URLField(blank=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='documents_d_owner_i_683479_idx'), models.Index(fields=['organization', 'status'], name='documents_d_organiz_b8cccc_idx')],
            },
        ),
    ]
