# Generated by Django 5.2.17 on 2026-10-04 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def snapshot_existing(apps, schema_editor):  # noqa: ARG001
    """Existing documents get their current content as their first recorded version."""
    Document = apps.get_model("documents", "Document")
    DocumentVersion = apps.get_model("documents", "DocumentVersion")
    DocumentVersion.objects.bulk_create(
        [
            DocumentVersion(document_id=doc.id, version=doc.version, content=doc.content, created_by_id=doc.owner_id)
            for doc in Document.objects.all().only("id", "version", "content", "owner_id")
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_rendered_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'ordering': ['version'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='uniq_document_version')],
            },
        ),
        migrations.RunPython(snapshot_existing, migrations.RunPython.noop),
    ]
