# Generated by Django 5.2.17 on 2026-10-04 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0006_seed_default_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('chat_messages', 'Chat Messages'), ('rag_queries', 'RAG Queries'), ('search_queries', 'Search Queries'), ('knowledge_documents', 'Knowledge Documents'), ('image_generations', 'Image Generations'), ('document_renders', 'Document Renders'), ('file_conversions', 'File Conversions'), ('workflow_executions', 'Workflow Executions'), ('agent_runs', 'Agent Runs'), ('analysis_runs', 'Analysis Runs'), ('api_calls', 'API Calls')], max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('credits_reserved', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('held', 'Held'), ('settled', 'Settled'), ('released', 'Released'), ('expired', 'Expired')], default='held', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_reservations', to='identity.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('chat_messages', 'Chat Messages'), ('rag_queries', 'RAG Queries'), ('search_queries', 'Search Queries'), ('knowledge_documents', 'Knowledge Documents'), ('image_generations', 'Image Generations'), ('document_renders', 'Document Renders'), ('file_conversions', 'File Conversions'), ('workflow_executions', 'Workflow Executions'), ('agent_runs', 'Agent Runs'), ('analysis_runs', 'Analysis Runs'), ('api_calls', 'API Calls')], max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.CharField(max_length=64)),
                ('basis', models.CharField(choices=[('provider_cost', 'Provider cost'), ('flat', 'Flat price')], max_length=20)),
                ('credits_charged', models.DecimalField(decimal_places=6, max_digits=20)),
                ('credits_uncollected', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('provider_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('model_run_count', models.PositiveIntegerField(default=0)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='identity.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='usage.usagereservation')),
            ],
        ),
        migrations.CreateModel(
            name='UsageReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('provider', models.CharField(max_length=60)),
                ('model_runs', models.PositiveIntegerField(default=0)),
                ('model_run_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('recomputed_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('billed_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unbilled_runs', models.PositiveIntegerField(default=0)),
                ('unbilled_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('provider_reported_cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('ok', 'Consistent'), ('drift', 'Drift detected')], default='ok', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_reconciliations', to='identity.organization')),
            ],
            options={
                'ordering': ('-date', 'provider'),
                'constraints': [models.UniqueConstraint(fields=('date', 'organization', 'provider'), name='uniq_reconciliation_day')],
            },
        ),
        migrations.AddIndex(
            model_name='usagereservation',
            index=models.Index(fields=['status', 'expires_at'], name='usage_res_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='usagereservation',
            index=models.Index(fields=['organization', 'feature', 'status'], name='usage_res_org_feature_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagereservation',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='uniq_reservation_source'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['organization', 'period', 'feature'], name='usage_rec_org_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='uniq_usage_record_source'),
        ),
    ]
