# Generated by Django 5.2.17 on 2026-10-05 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_user_country_code_user_dial_code'),
        ('usage', '0002_release_legacy_holds_and_append_only_ledgers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hour', models.DateTimeField()),
                ('observed_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('expected_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stddev_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('zscore', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_anomalies', to='identity.organization')),
            ],
            options={
                'ordering': ('-hour',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'hour'), name='uniq_cost_anomaly_org_hour'), models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('hour',), name='uniq_cost_anomaly_platform_hour')],
            },
        ),
    ]
