# Generated by Django 5.2.17 on 2026-08-17 06:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0004_organization_slug_organization_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_filename', models.CharField(max_length=500)),
                ('input_format', models.CharField(max_length=20)),
                ('output_format', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('input_bytes', models.PositiveBigIntegerField(default=0)),
                ('output_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reserved_credits', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('input_path', models.CharField(blank=True, max_length=1000)),
                ('output_path', models.CharField(blank=True, max_length=1000)),
                ('output_url', models.URLField(blank=True, max_length=1000)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to='identity.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='conversions_owner_i_cde83b_idx')],
            },
        ),
    ]
