# Generated by Django 5.2.17 on 2026-09-30 18:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_gateway', '0010_seed_llama_and_model_aliases'),
        ('identity', '0006_seed_default_roles'),
        ('jobs', '0006_callback_delivery_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCheckpoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thread_id', models.CharField(max_length=64)),
                ('checkpoint_ns', models.CharField(blank=True, default='', max_length=255)),
                ('checkpoint_id', models.CharField(max_length=64)),
                ('parent_checkpoint_id', models.CharField(blank=True, default='', max_length=64)),
                ('type', models.CharField(max_length=30)),
                ('checkpoint', models.BinaryField()),
                ('metadata_type', models.CharField(max_length=30)),
                ('metadata', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['thread_id', 'checkpoint_ns', '-checkpoint_id'], name='agents_agen_thread__5edf9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('thread_id', 'checkpoint_ns', 'checkpoint_id'), name='uniq_agent_checkpoint')],
            },
        ),
        migrations.CreateModel(
            name='AgentCheckpointWrite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thread_id', models.CharField(max_length=64)),
                ('checkpoint_ns', models.CharField(blank=True, default='', max_length=255)),
                ('checkpoint_id', models.CharField(max_length=64)),
                ('task_id', models.CharField(max_length=64)),
                ('idx', models.IntegerField()),
                ('channel', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('value', models.BinaryField()),
                ('task_path', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx'), name='uniq_agent_checkpoint_write')],
            },
        ),
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('graph', models.CharField(max_length=50)),
                ('system_prompt', models.TextField(blank=True)),
                ('model_alias', models.SlugField(blank=True, max_length=64)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('max_steps', models.PositiveIntegerField(default=12)),
                ('max_model_calls', models.PositiveIntegerField(default=6)),
                ('max_tool_calls', models.PositiveIntegerField(default=10)),
                ('max_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=10)),
                ('max_duration_seconds', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_definitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_definitions', to='identity.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph', models.CharField(max_length=50)),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('intent_source', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting for approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('input_text', models.TextField()),
                ('final_output', models.TextField(blank=True)),
                ('model_alias', models.SlugField(blank=True, max_length=64)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('budget', models.JSONField(blank=True, default=dict)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('model_calls', models.PositiveIntegerField(default=0)),
                ('tool_calls', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agents.agentdefinition')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='identity.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluator', models.CharField(max_length=50)),
                ('passed', models.BooleanField()),
                ('score', models.FloatField()),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='agents.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('node', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('gate', 'Gate'), ('router', 'Router'), ('model', 'Model call'), ('tool', 'Tool call'), ('system', 'System')], max_length=10)),
                ('outcome', models.CharField(choices=[('ok', 'OK'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='ok', max_length=10)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_steps', to='ai_gateway.modelrun')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace', to='agents.agentrun')),
            ],
            options={
                'ordering': ('run', 'sequence'),
            },
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_agent_org_slug'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['organization', '-created_at'], name='agents_agen_organiz_05d29c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'heartbeat_at'], name='agents_agen_status_37e365_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('organization', 'user', 'idempotency_key'), name='uniq_agent_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_agent_step_sequence'),
        ),
    ]
