# Generated by Django 5.2.17 on 2026-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_agent_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='tainted',
            field=models.BooleanField(default=False),
        ),
    ]
