# Generated by Django 5.2.17 on 2026-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_owner_i_96bc18_idx',
            old_name='assets_asse_owner_i_f137e6_idx',
        ),
    ]
