# Generated by Django 5.2.17 on 2026-10-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_upload_intents_and_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('organization', 'Organization')], db_index=True, default='private', max_length=20),
        ),
    ]
