# Generated by Django 5.2.17 on 2026-10-03 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_names(apps, schema_editor):  # noqa: ARG001
    Asset = apps.get_model("assets", "Asset")
    Asset.objects.filter(name="").update(name=models.F("original_filename"))


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_visibility'),
        ('conversations', '0007_chatrequest_dispatch_after'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConversationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_attachments', to='assets.asset')),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.conversation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'conversation'), name='uniq_conversation_attachment')],
            },
        ),
        migrations.RunPython(backfill_names, migrations.RunPython.noop),
    ]
