"""Application services that keep provider bytes and Django ownership aligned."""

from __future__ import annotations

import hashlib
from collections import defaultdict
from collections.abc import Iterable
from typing import Any

from django.db import transaction
from django.utils import timezone

from apps.assets.models import Asset
from apps.assets.supabase_storage import (
    FINGERPRINT_VERSION,
    organization_folder,
    provider_identity_fingerprint,
    upload_bytes,
)
from apps.events.outbox import add_outbox_event


def _register(
    content: bytes,
    *,
    owner: Any,
    organization: Any,
    file_name: str,
    folder: str,
    content_type: str,
    origin: str,
    provenance: dict[str, Any] | None,
) -> Asset:
    resource = upload_bytes(content, file_name=file_name, folder=folder, content_type=content_type)
    with transaction.atomic():
        asset = Asset.objects.create(
            owner=owner,
            organization=organization,
            storage_object_id=resource["key"],
            storage_key=resource["key"],
            storage_bucket=resource["bucket"],
            storage_url="",
            resource_type="file",
            format=file_name.rsplit(".", 1)[-1][:50] if "." in file_name else "",
            bytes=len(content),
            original_filename=file_name[:500],
            name=file_name[:500],
            metadata={
                "content_type": content_type,
            },
            checksum_sha256=hashlib.sha256(content).hexdigest(),
            provider_fingerprint=provider_identity_fingerprint(resource),
            provenance={
                "provider": "supabase-storage",
                "bucket": resource["bucket"],
                "key": resource["key"],
                "origin": origin,
                "registered_at": timezone.now().isoformat(),
                "fingerprintVersion": FINGERPRINT_VERSION,
                **(provenance or {}),
            },
            last_verified_at=timezone.now(),
        )
        add_outbox_event(
            "asset.created",
            str(asset.id),
            {
                "assetId": str(asset.id),
                "storageKey": asset.storage_key,
                "ownerId": str(asset.owner_id) if asset.owner_id else None,
                "organizationId": str(asset.organization_id),
                "resourceType": asset.resource_type,
                "bytes": asset.bytes,
                "origin": origin,
            },
        )
    return asset


def register_generated_asset(
    content: bytes,
    *,
    owner: Any,
    organization: Any,
    file_name: str,
    kind: str,
    content_type: str,
    provenance: dict[str, Any] | None = None,
) -> Asset:
    """Upload server-generated bytes privately into the tenant's ``kind`` folder."""
    return _register(
        content,
        owner=owner,
        organization=organization,
        file_name=file_name,
        folder=organization_folder(organization.id, kind),
        content_type=content_type,
        origin="server-generated",
        provenance=provenance,
    )


def register_uploaded_asset(
    content: bytes, *, owner: Any, organization: Any, file_name: str, content_type: str
) -> Asset:
    """Register a user upload received by the API (already size/type verified)."""
    return _register(
        content,
        owner=owner,
        organization=organization,
        file_name=file_name,
        folder=organization_folder(organization.id, f"uploads/{owner.id}"),
        content_type=content_type,
        origin="api-upload",
        provenance={"uploaded_by": str(owner.id)},
    )


def asset_references(asset_ids: Iterable[Any]) -> dict[str, list[str]]:
    """Live consumers of each asset as ``kind:id`` strings (batched, one query per kind)."""
    ids = [str(value) for value in asset_ids]
    references: dict[str, list[str]] = defaultdict(list)
    if not ids:
        return references
    from apps.ai_gateway.models import GeneratedImage
    from apps.analytics.models import AnalysisRun, Dataset, Visualization
    from apps.assets.models import ConversationAttachment
    from apps.conversions.models import ConversionJob
    from apps.documents.models import Document as AuthoredDocument
    from apps.knowledge.models import Source

    for source_id, asset_id in Source.objects.filter(config__asset_id__in=ids).values_list(
        "id", "config__asset_id"
    ):
        references[str(asset_id)].append(f"knowledge-source:{source_id}")
    lookups: list[tuple[str, Any, str]] = [
        ("dataset", Dataset.objects, "asset_id"),
        ("analysis-run", AnalysisRun.objects, "result_asset_id"),
        ("visualization", Visualization.objects, "artifact_asset_id"),
        ("visualization-spec", Visualization.objects, "spec_asset_id"),
        ("document", AuthoredDocument.objects, "rendered_asset_id"),
        ("conversion", ConversionJob.objects, "output_asset_id"),
        ("image", GeneratedImage.objects, "asset_id"),
        ("conversation", ConversationAttachment.objects, "asset_id"),
    ]
    for kind, manager, field in lookups:
        value_field = "conversation_id" if kind == "conversation" else "id"
        for owner_id, asset_id in manager.filter(**{f"{field}__in": ids}).values_list(value_field, field):
            references[str(asset_id)].append(f"{kind}:{owner_id}")
    return references


def soft_delete_asset(asset: Asset | None) -> None:
    if asset is None or asset.status == Asset.Status.DELETED:
        return
    with transaction.atomic():
        asset.status = Asset.Status.DELETED
        asset.deleted_at = timezone.now()
        asset.deletion_error = ""
        asset.save(update_fields=["status", "deleted_at", "deletion_error", "updated_at"])
        add_outbox_event(
            "asset.deleted",
            str(asset.id),
            {
                "assetId": str(asset.id),
                "storageKey": asset.storage_key,
                "ownerId": str(asset.owner_id) if asset.owner_id else None,
                "organizationId": str(asset.organization_id),
            },
        )


def restore_asset(asset: Asset) -> bool:
    """Undo a soft delete while the provider object still exists."""
    if asset.status != Asset.Status.DELETED or asset.provider_deleted_at is not None:
        return False
    with transaction.atomic():
        asset.status = Asset.Status.READY
        asset.deleted_at = None
        asset.save(update_fields=["status", "deleted_at", "updated_at"])
        add_outbox_event(
            "asset.restored",
            str(asset.id),
            {"assetId": str(asset.id), "organizationId": str(asset.organization_id)},
        )
    return True
