"""Application services that keep provider bytes and Django ownership aligned."""

from __future__ import annotations

import hashlib

from django.db import transaction
from django.utils import timezone

from apps.assets.imagekit import (
    provider_identity_fingerprint,
    upload_bytes_to_imagekit_details,
)
from apps.assets.models import Asset
from apps.events.outbox import add_outbox_event


def register_generated_asset(
    content: bytes,
    *,
    owner,
    organization,
    file_name: str,
    folder: str,
    content_type: str,
    provenance: dict | None = None,
) -> Asset:
    """Upload server-generated bytes and atomically register their ownership."""
    resource = upload_bytes_to_imagekit_details(
        content,
        file_name=file_name,
        folder=folder,
        content_type=content_type,
    )
    with transaction.atomic():
        asset = Asset.objects.create(
            owner=owner,
            organization=organization,
            imagekit_file_id=resource["fileId"],
            imagekit_file_path=resource["filePath"],
            secure_url=resource["url"],
            resource_type=resource["fileType"],
            format=str(resource.get("format") or file_name.rsplit(".", 1)[-1])[:50],
            bytes=len(content),
            original_filename=file_name,
            metadata={
                "thumbnail_url": resource.get("thumbnailUrl"),
                "version_info": resource.get("versionInfo"),
                "content_type": content_type,
            },
            checksum_sha256=hashlib.sha256(content).hexdigest(),
            provider_fingerprint=provider_identity_fingerprint(resource),
            provenance={
                "provider": "imagekit",
                "origin": "server-generated",
                "registered_at": timezone.now().isoformat(),
                **(provenance or {}),
            },
        )
        add_outbox_event(
            "asset.created",
            str(asset.id),
            {
                "assetId": str(asset.id),
                "fileId": asset.imagekit_file_id,
                "ownerId": str(asset.owner_id),
                "resourceType": asset.resource_type,
                "bytes": asset.bytes,
            },
        )
    return asset


def soft_delete_asset(asset: Asset | None) -> None:
    if asset is None or asset.status == Asset.Status.DELETED:
        return
    asset.status = Asset.Status.DELETED
    asset.deleted_at = timezone.now()
    asset.deletion_error = ""
    asset.save(update_fields=["status", "deleted_at", "deletion_error", "updated_at"])
    add_outbox_event(
        "asset.deleted",
        str(asset.id),
        {"assetId": str(asset.id), "fileId": asset.imagekit_file_id, "ownerId": str(asset.owner_id)},
    )
