# Generated by Django 5.2.17 on 2026-10-04 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0006_seed_default_roles'),
        ('jobs', '0007_workflowrun_attempt_workflowrun_deadline_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('job', 'Job workflow'), ('event', 'Event-triggered workflow'), ('request', 'Synchronous request'), ('error', 'Error workflow')], max_length=10)),
                ('definition', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('webhook_path', models.CharField(blank=True, max_length=255)),
                ('task_types', models.JSONField(blank=True, default=list)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('timeout_seconds', models.PositiveIntegerField(default=1800)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('required_credentials', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('n8n_workflow_id', models.CharField(blank=True, max_length=64)),
                ('n8n_active', models.BooleanField(default=False)),
                ('synced_checksum', models.CharField(blank=True, max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key', '-version'),
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='uniq_workflow_key_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('key',), name='uniq_active_workflow_per_key')],
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('workflow_key', models.SlugField(default='scheduled-automation', max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('input', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to=settings.AUTH_USER_MODEL)),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='identity.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='orch_automation_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEventDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('accepted', 'Accepted by n8n'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('n8n_execution_id', models.CharField(blank=True, max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orchestration.workflowdefinition')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_deliveries', to='identity.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='orch_delivery_due_idx'), models.Index(fields=['event_type', '-created_at'], name='orch_delivery_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('definition', 'event_id'), name='uniq_delivery_per_event')],
            },
        ),
    ]
