# Generated by Django 5.2.17 on 2026-10-04 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('restore_drill', 'Database restore drill'), ('dlq_drill', 'Dead-letter recovery drill'), ('saturation_drill', 'Celery/Kafka saturation drill'), ('load_test', 'Load test'), ('spike_test', 'Spike test'), ('soak_test', 'Soak test'), ('streaming_test', 'SSE streaming concurrency test'), ('rag_evaluation', 'RAG quality evaluation'), ('rag_security', 'RAG security evaluation'), ('chaos_experiment', 'Chaos experiment'), ('capacity_audit', 'Capacity audit'), ('release_gate', 'Release gate')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('environment', models.CharField(blank=True, max_length=40)),
                ('git_sha', models.CharField(blank=True, max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['kind', 'status', '-started_at'], name='ops_run_kind_idx')],
            },
        ),
    ]
