import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("identity", "0006_seed_default_roles"), ("assets", "0006_asset_lifecycle_and_provenance")]
    operations = [
        migrations.CreateModel(name="Dataset", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=255)), ("mime_type", models.CharField(default="text/csv", max_length=100)), ("inline_data", models.TextField(blank=True)), ("schema", models.JSONField(blank=True, default=dict)), ("row_count", models.PositiveIntegerField(default=0)), ("byte_size", models.PositiveBigIntegerField(default=0)), ("is_shared", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="datasets", to="assets.asset")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to="identity.organization")), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="AnalysisRun", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="queued", max_length=12)), ("transform", models.JSONField(blank=True, default=dict)), ("profile", models.JSONField(blank=True, default=dict)), ("result_schema", models.JSONField(blank=True, default=dict)), ("error_message", models.TextField(blank=True)), ("started_at", models.DateTimeField(blank=True, null=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analysis_runs", to="analytics.dataset")), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analysis_runs", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="DatasetGrant", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("permission", models.CharField(choices=[("view", "View"), ("analyze", "Analyze")], default="view", max_length=12)), ("created_at", models.DateTimeField(auto_now_add=True)), ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="analytics.dataset")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dataset_grants", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Visualization", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("kind", models.CharField(choices=[("bar", "Bar"), ("line", "Line"), ("scatter", "Scatter"), ("histogram", "Histogram")], max_length=20)), ("x_column", models.CharField(max_length=255)), ("y_column", models.CharField(blank=True, max_length=255)), ("status", models.CharField(choices=[("queued", "Queued"), ("ready", "Ready"), ("failed", "Failed")], default="queued", max_length=12)), ("plotly_spec", models.JSONField(blank=True, default=dict)), ("artifact_url", models.URLField(blank=True)), ("artifact_checksum_sha256", models.CharField(blank=True, max_length=64)), ("result_schema", models.JSONField(blank=True, default=dict)), ("error_message", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("analysis_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visualizations", to="analytics.analysisrun"))]),
        migrations.AddIndex(model_name="dataset", index=models.Index(fields=("organization", "-created_at"), name="analytics_d_organiz_7d242d_idx")),
        migrations.AddIndex(model_name="analysisrun", index=models.Index(fields=("dataset", "-created_at"), name="analytics_a_dataset_2d02d7_idx")),
        migrations.AddIndex(model_name="analysisrun", index=models.Index(fields=("status", "created_at"), name="analytics_a_status_5e32e7_idx")),
        migrations.AddIndex(model_name="visualization", index=models.Index(fields=("analysis_run", "-created_at"), name="analytics_v_analysis_5b15c4_idx")),
        migrations.AddConstraint(model_name="datasetgrant", constraint=models.UniqueConstraint(fields=("dataset", "user"), name="uniq_dataset_grant")),
    ]
