# Generated by Django 5.2.17 on 2026-10-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("assets", "0007_upload_intents_and_integrity"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="visualization",
            new_name="analytics_v_analysi_5b15c4_idx",
            old_name="analytics_v_analysis_5b15c4_idx",
        ),
        migrations.RemoveField(
            model_name="visualization",
            name="artifact_url",
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="result_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_results",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="result_preview",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dataset",
            name="source_checksum_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="visualization",
            name="artifact_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_visualizations",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="visualization",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visualization",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=12,
            ),
        ),
    ]
