# Generated by Django 5.2.17 on 2026-10-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analytics_v_analysis_5b15c4_idx_analytics_v_analysi_5b15c4_idx_and_more'),
        ('assets', '0009_asset_registry_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='visualization',
            name='color_column',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visualization',
            name='spec_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_specs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='kind',
            field=models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('scatter', 'Scatter'), ('histogram', 'Histogram'), ('area', 'Area'), ('box', 'Box'), ('pie', 'Pie')], max_length=20),
        ),
    ]
