# Generated by Django 5.2.17 on 2026-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatrequest',
            new_name='conversatio_owner_i_979610_idx',
            old_name='conversatio_owner_i_26f038_idx',
        ),
        migrations.RenameIndex(
            model_name='chatrequest',
            new_name='conversatio_status_9e95fd_idx',
            old_name='conversatio_status_836802_idx',
        ),
    ]
