# Generated by Django 5.2.17 on 2026-09-20 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_rename_conversatio_owner_i_26f038_idx_conversatio_owner_i_979610_idx_and_more'),
        ('identity', '0004_organization_slug_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_requests', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='identity.organization'),
        ),
    ]
