# Generated by Django 5.2.17 on 2026-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_chatrequest_durable_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='dispatch_after',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
